// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const overlay: string;
export const content: string;
export const closeBtn: string;
export const menuIcon: string;
