// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const box: string;
export const content: string;
export const caption: string;
export const zoom: string;
export const close: string;
export const closefocus: string;
