// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const box: string;
export const arrowIcon: string;
export const triangleBox: string;
export const triangle: string;
export const flag: string;
