// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const block_title: string;
export const leaf: string;
export const section: string;
export const section_text: string;
export const section_image: string;
